language: android
jdk: oraclejdk7
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
  - MALLOC_ARENA_MAX=2
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-support
  - extra-android-m2repository
script:
  - ./gradlew build --stacktrace
